# Generated by Django 5.1.4 on 2024-12-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_do_produto', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
